[Breaking] Set workspace_id to a string instead of int for Pulumi
pulumi/pulumi-databricks pull request #435
Opened 2024-04-24 01:03 UTC by iwahbe

Fixes https://github.com/pulumi/pulumi-databricks/issues/55

This should fix the problem. The bridge has tests that demonstrate that strings don't loose information when converted to `int64` for the upstream provider.

I have been unable to build a full test that uses MetastoreAssignment. It's a non-trivial resource to instantiate.

BREAKING: Migration Guide

`workspace_id` has changed type from a `int` to `string`. Each call-site will need to be addressed.

2024-04-24 10:16 UTC, VenelinMartinov requested changes
We should add a test with at least one of the resources - otherwise it looks good.

2024-04-24 10:16 UTC, VenelinMartinov commented
Is this a major version release?

2024-04-24 16:48 UTC, iwahbe commented
> We should add a test with at least one of the resources - otherwise it looks good.

Yes. We need this to merge.

> Is this a major version release?

I don't think so, but I'm open to convincing. My thought is that while this is a breaking change, it is a breaking change in a part of the provider that *did not* work previously, so we are not breaking working code.

2024-04-25 22:45 UTC, iwahbe commented
The requirements to creating a simple workspace to test against are here: https://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/aws-workspace. The basic diagram has 19 resources across databricks and AWS. We have bridge tests in place that verify translating between a string and int64 work. I'm comfortable merging without tests for this repo.

2024-04-26 10:33 UTC, VenelinMartinov approved these changes
mws_networks doesn't look too bad: https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/mws_networks#creating-a-databricks-on-aws-workspace

anyway, feel free to merge

2024-04-26 17:37 UTC, iwahbe commented
> mws_networks doesn't look too bad: https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/mws_networks#creating-a-databricks-on-aws-workspace
> 
> anyway, feel free to merge

That's the resource that links to pretty large "how to actually use this guides":

- https://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/aws-workspace
- https://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/gcp-workspace

2024-04-26 17:37 UTC, merged